### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by rnshah9**

### CODE REVIEW

**Review by xansec — APPROVED** [review]
LGTM!

**Comment by xansec** [comment]
Going through some of these, this appears to be failing:
https://github.com/mayhemheroes/lyra/actions/runs/3759067073

**Comment by rnshah9** [comment]
I tried to fix this but there is an upstream package that is broken, due to [this unresolved issue](https://github.com/tensorflow/tensorflow/issues/57947) that was introduced sometime after I submitted this. Not sure if I should just wait until it's resolved.

**Comment by xansec** [comment]
Ok, read through the bug. It's possible that this will remain stale. We can keep an eye on it for now.

**Pull request merged**
